import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: PeriodicTable(),
    );
  }
}

class PeriodicTable extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Periodic Table')),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: [
            buildElementRow([
              "H",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "He"
            ]),
            buildElementRow([
              "Li",
              "Be",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "B",
              "C",
              "N",
              "O",
              "F",
              "Ne"
            ]),
            buildElementRow([
              "Na",
              "Mg",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "Al",
              "Si",
              "P",
              "S",
              "Cl",
              "Ar"
            ]),
            buildElementRow([
              "K",
              "Ca",
              "Sc",
              "Ti",
              "V",
              "Cr",
              "Mn",
              "Fe",
              "Co",
              "Ni",
              "Cu",
              "Zn",
              "Ga",
              "Ge",
              "As",
              "Se",
              "Br",
              "Kr"
            ]),
            buildElementRow([
              "Rb",
              "Sr",
              "Y",
              "Zr",
              "Nb",
              "Mo",
              "Tc",
              "Ru",
              "Rh",
              "Pd",
              "Ag",
              "Cd",
              "In",
              "Sn",
              "Sb",
              "Te",
              "I",
              "Xe"
            ]),
            buildElementRow([
              "Cs",
              "Ba",
              "La",
              "Hf",
              "Ta",
              "W",
              "Re",
              "Os",
              "Ir",
              "Pt",
              "Au",
              "Hg",
              "Tl",
              "Pb",
              "Bi",
              "Po",
              "At",
              "Rn"
            ]),
            buildElementRow([
              "Fr",
              "Ra",
              "Ac",
              "Rf",
              "Db",
              "Sg",
              "Bh",
              "Hs",
              "Mt",
              "Ds",
              "Rg",
              "Cn",
              "Nh",
              "Fl",
              "Mc",
              "Lv",
              "Ts",
              "Og"
            ]),
          ],
        ),
      ),
    );
  }

  Row buildElementRow(List<String> elements) {
    return Row(
      children: elements
          .map((element) => Expanded(
                child: Container(
                  height: 40,
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.black),
                  ),
                  child: Text(element),
                ),
              ))
          .toList(),
    );
  }
}
